[package]
name = "iai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
iai = "0.1"

[[bench]]
name = "bench_main"
harness = false
